# Generated by Django 2.2.3 on 2019-07-10 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20190710_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 15, 1, 11, 656415, tzinfo=utc)),
        ),
    ]
