# Generated by Django 2.2.3 on 2019-07-11 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190710_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 13, 28, 25, 868956, tzinfo=utc)),
        ),
    ]
