# Generated by Django 2.2.3 on 2019-07-11 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20190711_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 15, 3, 8, 297965, tzinfo=utc)),
        ),
    ]
