# Generated by Django 2.2.3 on 2019-07-12 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20190711_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 15, 8, 52, 764168, tzinfo=utc)),
        ),
    ]
