# Generated by Django 2.2.3 on 2019-07-12 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20190712_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 16, 21, 18, 423318, tzinfo=utc)),
        ),
    ]
