# Generated by Django 2.2.3 on 2019-07-14 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20190714_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 14, 25, 48, 646884, tzinfo=utc)),
        ),
    ]
