# Generated by Django 2.2.3 on 2019-07-15 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20190714_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 11, 32, 26, 201462, tzinfo=utc)),
        ),
    ]
