# Generated by Django 2.2.3 on 2019-07-04 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190704_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 21, 3, 24, 909055, tzinfo=utc)),
        ),
    ]
