# Generated by Django 2.2.3 on 2019-07-10 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190704_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 13, 21, 15, 902454, tzinfo=utc)),
        ),
    ]
