# Generated by Django 2.2.3 on 2019-07-12 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190712_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_date_posted',
        ),
        migrations.AddField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 16, 11, 3, 187097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 16, 11, 3, 186669, tzinfo=utc)),
        ),
    ]
