# Generated by Django 2.2.3 on 2019-07-14 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190712_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 12, 53, 58, 504832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 12, 53, 58, 505294, tzinfo=utc)),
        ),
    ]
