# Generated by Django 2.2.3 on 2019-07-15 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190714_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 14, 3, 23, 245485, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 14, 3, 23, 246174, tzinfo=utc)),
        ),
    ]
