# Generated by Django 2.2.3 on 2019-07-15 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190715_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 14, 33, 21, 774024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 14, 33, 21, 774617, tzinfo=utc)),
        ),
    ]
